Test.assert_equals(get_socks('Henry',[]), [])
Test.assert_equals(get_socks('Punky',[]), [])
Test.assert_equals(get_socks('Henry',['green']), [])
Test.assert_equals(get_socks('Punky',['green']), [])
Test.assert_equals(get_socks('Punky',['pink','argyle','argyle']), ['pink', 'argyle'])
Test.assert_equals(get_socks('Henry',['pink','argyle','argyle']), ['argyle', 'argyle'])
Test.assert_equals(get_socks('Henry',['red','blue','blue','green']), ['blue', 'blue'])
Test.assert_equals(get_socks('Punky',['red','blue','blue','green']), ['red', 'blue'])
Test.assert_equals(get_socks('Punky',['pink','pink','pink','pink']), [])
Test.assert_equals(get_socks('Punky',['blue','blue','blue','green','green']), ['blue', 'green'])
Test.assert_equals(get_socks('Henry',['green','blue','pink','argyle']), [])
Test.assert_equals(get_socks('Henry',['argyle','green','dirty sock','argyle']), ['argyle', 'argyle'])
Test.assert_equals(get_socks('Henry',["argyle", "argyle", "torn sock", "argyle"]), ['argyle', 'argyle'])
